apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - example.air.com
  resources:
  - '*'
  verbs:
  - get
  - list
  - create
  - delete