apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: k8s-fms
  template:
    metadata:
      labels:
        app: k8s-fms
    spec:
      serviceAccountName: {{ .Values.appName }}
      volumes:
      - name: shared-data
        emptyDir: {}
      initContainers:
      - name: init-script
        image: natrufthr/k8sfmsinit:v1
        volumeMounts:
        - name: shared-data
          mountPath: /app/data
        command: ["/entrypoint.sh"]
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        volumeMounts:
        - name: shared-data
          mountPath: /app/data
        env:
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"