apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hubs.example.air.com
spec:
  group: example.air.com
  names:
    kind: Hub
    plural: hubs
  scope: Namespaced
  versions:
   - name: v1
     served: true
     storage: true
     schema:
       openAPIV3Schema:
         type: object
         properties:
           spec:
             type: object
             properties:
               airLineName:
                 type: string
     additionalPrinterColumns:
       - name: AirLineName
         type: string
         description: "The airline name"
         jsonPath: .spec.airLineName