apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: spokes.example.air.com
spec:
  group: example.air.com
  names:
    kind: Spoke
    plural: spokes
  scope: Namespaced
  versions:
   - name: v1
     served: true
     storage: true
     schema:
       openAPIV3Schema:
         type: object
         properties:
           spec:
             type: object
             properties:
               hubName:
                 type: string
               airLineName:
                 type: string
     additionalPrinterColumns:
       - name: HubName
         type: string
         description: "The hub name"
         jsonPath: .spec.hubName
       - name: AirLineName
         type: string
         description: "The airline name"
         jsonPath: .spec.airLineName