apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-fms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-fms
  template:
    metadata:
      labels:
        app: k8s-fms
    spec:
      serviceAccountName: k8s-fms
      volumes:
      - name: shared-data
        emptyDir: {}
      initContainers:
      - name: init-script
        image: natrufthr/k8sfmsinit:v1
        volumeMounts:
        - name: shared-data
          mountPath: /app/data
        command: ["/entrypoint.sh"]
      containers:
      - name: k8s-fms
        image: natrufthr/k8sfms:v7
        command: ["sleep", "365d"]
        # Add your container configuration here
        volumeMounts:
        - name: shared-data
          mountPath: /app/data