# apiVersion: apiextensions.k8s.io/v1
# kind: CustomResourceDefinition
# metadata:
#   name: flights.example.air.com
# spec:
#   group: example.air.com
#   names:
#     kind: Flight
#     plural: flights
#   scope: Namespaced
#   versions:
#    - name: v1
#      served: true
#      storage: true
#      schema:
#        openAPIV3Schema:
#          type: object
#          properties:
#            spec:
#              type: object
#              properties:
#                going:
#                  type: string
#                leaving:
#                  type: string
#                airLineName:
#                  type: string
#      additionalPrinterColumns:
#        - name: going
#          type: string
#          description: "airport flight is going to"
#          jsonPath: .spec.going
#        - name: leaving
#          type: string
#          description: "airport flight is leaving"
#          jsonPath: .spec.leaving
#        - name: AirLineName
#          type: string
#          description: "The airline name"
#          jsonPath: .spec.airLineName